helpdeskproject/helpdeskapp/urls.py
from django.urls import path
from . import views

app_name = 'helpdeskapp'

urlpatterns = [
    path('adds/', views.adds, name='adds'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('mylist/', views.mylist, name='mylist'),
    path('query_data/', views.query_data, name='query_data'),
    path('doaction/<action>', views.DoAction, name='DoAction'),
    path('export_pdf/', views.export_pdf, name='export-pdf'),
    path('export_excel/', views.export_excel, name='export-excel'),
    path('export_blank_pdf/', views.export_blank_pdf, name='export-blank-pdf'),
]

helpdeskproject/helpdeskproject/urls.py
from django.contrib import admin
from django.urls import path, include
from helpdeskapp import views
from django.conf import settings
from django.conf.urls.static import static
#from helpdeskapp.views import mychartview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('helpdeskapp/', include('helpdeskapp.urls')),
    path('helpdeskusers/', include('helpdeskusers.urls')),
    #path('', mychartview.as_view(), name='home'),
    path('', views.mychartview, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpdeskproject/helpdeskapp/forms.py
from django import forms
from .models import AddTicket
from django.forms import widgets

class AddTicketForm(forms.ModelForm):

    class Meta:

        model = AddTicket

        fields = '__all__'

        widgets = {
            'issue_date': widgets.DateInput(attrs={'type': 'date'}),
            'job_complete_date': widgets.DateInput(attrs={'type': 'date'}),
            'give_back_date': widgets.DateInput(attrs={'type': 'date'}),
            'spare_device_date': widgets.DateInput(attrs={'type': 'date'}),
            'got_back_spare_device_date': widgets.DateInput(attrs={'type': 'date'}),
        }

helpdeskproject/helpdeskapp/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from .models import AddTicket
from .forms import AddTicketForm
import requests
import datetime 

from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile

import xlwt

from django.db.models import Count


# Create your views here.
'''
def home(request):
    members = User.objects.count()
    processing_count = AddTicket.objects.filter(status = 'PROCESSING').count()
    complete_count = AddTicket.objects.filter(status= 'COMPLETE').count()
    cancel_count = AddTicket.objects.filter(status='CANCEL').count()

    context = {
        'members': members,
        'processing_count': processing_count,
        'complete_count': complete_count,
        'cancel_count': cancel_count,
    }
    return render(request, 'helpdeskapp/home.html', context)
'''
'''
class mychartview(TemplateView):
    template_name = 'helpdeskapp/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["qs"] = AddTicket.objects.all()
        return context
'''
#Dashboard Charts
def mychartview(request):
    queryset = AddTicket.objects.order_by('status').values('status').annotate(status_count=Count('status'))

    queryuser = User.objects.all().values('is_staff').annotate(total=Count('is_staff'))

    data = list(queryset.values_list('status_count', flat= True))
    labels = list(queryset.values_list('status', flat=True))

    data2 = list(queryuser.values_list('total', flat=True))
    labels2 = list(queryuser.values_list('is_staff', flat=True))

    
    context = {'queryset': queryset,
                'queryuser': queryuser,
                'data': data,
                'labels': labels,
                'data2': data2,
                'labels2': labels2          
    }
    return render(request, 'helpdeskapp/home.html', context)

#เปิด Ticket แล้ว save form ลง database
@login_required
def adds(request):
    if request.method == 'POST':
        form = AddTicketForm(request.POST, request.FILES)

        if form.is_valid():
            
            helpdeskapp = form.save(commit=False)
            helpdeskapp.user = request.user
            helpdeskapp.save()
            messages.success(request, f'บันทึกข้อมูลเรียบร้อยแล้ว')

            last_id = helpdeskapp.pk 
            form_detail = AddTicket.objects.get(id__exact = last_id)
            #print(form_detail.id)
            
            '''if form_detail.place == None:
                form_detail.place = "ไม่มีข้อมูล"'''
            
            
            url = 'https://notify-api.line.me/api/notify'
            token = 'xuVeGPqonotndJpC5VAqH0E51FiimOlnkDhXg5t5S62'
            headers = {'content-type':'application/x-www-form-urlencoded','Authorization':'Bearer '+token}

            msg = ("หมายเลขงาน : "+ str(form_detail.id) +",\r\n\r\nชื่อ Login ผู้แจ้งปัญหา : "+ form_detail.user.username +",\r\n\r\nประจำงวดงาน : "+ form_detail.installment.installment +",\r\n\r\nสถานที่ตั้งอุปกรณ์ : "+ str(form_detail.place) +", \r\n\r\nหน่วยงาน : "+ form_detail.institution +",\r\n\r\nผู้แจ้งปัญหา : "+ form_detail.informer +",\r\n\r\nเบอร์โทรศัพท์ : "+ form_detail.phone_number +",\r\n\r\nวันที่แจ้งปัญหา : "+ str(form_detail.issue_date) +",\r\n\r\nอุปกรณ์ : "+ str(form_detail.device_name) +",\r\n\r\nยี่ห้อ : "+ form_detail.brand +",\r\n\r\nรุ่น : "+ form_detail.model +",\r\n\r\nหมายเลขคุรุภัณฑ์ : "+ form_detail.inventory_number +",\r\n\r\nหมายเลขประจำอุปกรณ์ : "+ form_detail.serial_number +",\r\n\r\nปัญหาที่เกิดขึ้น : "+ form_detail.issue +",\r\n\r\nผู้รับผิดชอบ : "+ form_detail.responsibility +",\r\n\r\nรายละเอียดการซ่อม : "+ form_detail.detail +",\r\n\r\nวันที่ซ่อมเสร็จ : "+ str(form_detail.job_complete_date) +",\r\n\r\nสถานะซ่อมบำรุง : "+ form_detail.status +" ")


            r = requests.post(url, headers=headers, data = {'message':msg})
            print(r.text)

            #print(form_detail.status)
            
            return redirect('helpdeskapp:mylist')
        else:
            print('Error :', form.errors)
           
    form = AddTicketForm()
    return render(request, 'helpdeskapp/adds.html', {'form': form})

#แก้ไขฟอร์ม Ticket แล้ว Update ลง Database
@login_required
def edit(request, id):
    addticket_edit = AddTicket.objects.get(id=id)
    form = AddTicketForm(instance=addticket_edit)

    if request.method == 'POST':
        form = AddTicketForm(request.POST, instance=addticket_edit)
        if form.is_valid():
            helpdeskapp = form.save(commit=False)
            helpdeskapp.user = request.user
            helpdeskapp.save()
            messages.success(request, f'แก้ไขข้อมูลเรียบร้อยแล้ว')
            print(helpdeskapp.modified_data())

            last_id = helpdeskapp.pk 
            form_detail = AddTicket.objects.get(id__exact = last_id)
            #print(form_detail.id)


            url = 'https://notify-api.line.me/api/notify'
            token = 'xuVeGPqonotndJpC5VAqH0E51FiimOlnkDhXg5t5S62'
            headers = {'content-type':'application/x-www-form-urlencoded','Authorization':'Bearer '+token}

            msg = ("หมายเลขงาน : "+ str(form_detail.id) +",\r\n\r\nชื่อ Login ผู้แจ้งปัญหา : "+ form_detail.user.username +",\r\n\r\nประจำงวดงาน : "+ form_detail.installment.installment +",\r\n\r\nสถานที่ตั้งอุปกรณ์ : "+ str(form_detail.place) +", \r\n\r\nหน่วยงาน : "+ form_detail.institution +",\r\n\r\nผู้แจ้งปัญหา : "+ form_detail.informer +",\r\n\r\nเบอร์โทรศัพท์ : "+ form_detail.phone_number +",\r\n\r\nวันที่แจ้งปัญหา : "+ str(form_detail.issue_date) +",\r\n\r\nอุปกรณ์ : "+ str(form_detail.device_name) +",\r\n\r\nยี่ห้อ : "+ form_detail.brand +",\r\n\r\nรุ่น : "+ form_detail.model +",\r\n\r\nหมายเลขคุรุภัณฑ์ : "+ form_detail.inventory_number +",\r\n\r\nหมายเลขประจำอุปกรณ์ : "+ form_detail.serial_number +",\r\n\r\nปัญหาที่เกิดขึ้น : "+ form_detail.issue +",\r\n\r\nผู้รับผิดชอบ : "+ form_detail.responsibility +",\r\n\r\nรายละเอียดการซ่อม : "+ form_detail.detail +",\r\n\r\nวันที่ซ่อมเสร็จ : "+ str(form_detail.job_complete_date) +",\r\n\r\nสถานะซ่อมบำรุง : "+ form_detail.status +" ")


            r = requests.post(url, headers=headers, data = {'message':msg})
            print(r.text)

            #print(form_detail.status)
            
            
            return redirect('helpdeskapp:mylist')
        else:
            print('Error :', form.errors)

    context = {
        'form': form,
        'addticket_edit': addticket_edit
    
    }
    return render(request, 'helpdeskapp/edit.html', context)

@login_required
def mylist(request):
    ticket_list = AddTicket.objects.all()
    #print([e.status for e in AddTicket.objects.all()])
    context = {'ticket_list': ticket_list}
    return render(request, 'helpdeskapp/mylist.html', context)


@login_required
def DoAction(request, action):
    username = str(request.user.username).lower()
    if username.startswith("admin"):
        print('username')
        data_list = AddTicket.objects.filter(status = action)
        print('data_list')
    else:
        data_list = AddTicket.objects.filter(status = action, user = request.user)
    context = {'data_list': data_list, 'action': action}
    return render(request, 'helpdeskapp/doaction.html', context)


@login_required
def query_data(request):
    query_list = AddTicket.objects.all()

    context = {'query_list': query_list}
    return render(request, 'helpdeskapp/query.html', context)

# Export PDF Report
@login_required
def export_pdf(request):

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; attachment; filename=Reports' + \
        str(datetime.datetime.now()) + '.pdf'

    response['Content-Transfer-Encoding'] = 'binary'

    reports = AddTicket.objects.filter(user=request.user)

    html_string = render_to_string(
        'helpdeskapp/pdf_output.html', {'reports': reports})
    html = HTML(string=html_string)

    result = html.write_pdf()

    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())
    
    return response

# Export XLS EXCEL Report
@login_required
def export_excel(request):

    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=Reports' + \
        str(datetime.datetime.now()) + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Reports')
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['หมายเลขงาน','ประจำงวดงาน', 'ชื่อ Login ผู้แจ้งปัญหา', 'สถานที่ตั้งอุปกรณ์',
        'หน่วยงาน', 'วันที่แจ้งปัญหา', 'ผู้แจ้งปัญหา', 'ปัญหาที่เกิดขึ้น', 'อุปกรณ์',
        'ยี่ห้อ', 'รุ่น', 'หมายเลขคุรุภัณฑ์', 'หมายเลขประจำอุปกรณ์', 'มอบหมายงาน',
        'รายละเอียดในการซ่อม', 'งานค้าง', 'วันที่ซ่อมเสร็จ', 'วันที่ส่งคืนอุปกรณ์' ,'อุปกรณ์สำรอง', 'วันที่สำรองอุปกรณ์' 
    ]

    
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()

    rows = AddTicket.objects.filter(user=request.user).values_list(
        'id','installment__installment', 'user__username', 'place', 'institution', 'issue_date',
        'informer', 'issue', 'device_name__device_name', 'brand', 'model',
        'inventory_number', 'serial_number', 'delegation', 'detail',
        'blocklog', 'job_complete_date', 'give_back_date', 'spare_device' , 'spare_device_date'
    )
    
    for row in rows:
        row_num += 1

        
        for col_num in range(len(row)):
        #for col_num, row in enumerate(rows):
            ws.write(row_num, col_num, str(row[col_num]), font_style) 

    wb.save(response)

    return response

# Export Blank PDF
@login_required

helpdeskproject/helpdeskapp/templates/helpdeskapp/adds.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">เพิ่ม Ticket</h1>
    <div class="row">
        <div class="col-xs-12 col-md-12">
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    {{form.user | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.installment | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.place | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.institution | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.informer | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.phone_number | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.issue_date | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.issue | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.device_name | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.brand | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.model | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.inventory_number | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.serial_number | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.os_system_name | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.delegation | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.responsibility | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.detail | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.blocklog | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.status | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.job_complete_date | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.reason | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.give_back_date | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.spare_device | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.serial_number_spare | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.spare_device_date | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.got_back_spare_device_date | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.change_device | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.change_device_name | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.change_for_brand | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.change_for_model | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.change_for_serial_number | as_crispy_field}}
                </div>
                <div class="mb-3">
                    {{form.upload_image_before | as_crispy_field}}
                </div>
                <button type="submit" class="btn btn-outline-primary mb-4">บันทึก</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

helpdeskproject/helpdeskapp/templates/helpdeskapp/blank_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report HelpDesk</title>
    <style>
        @page {
        size: A4;
        margin: 2.5cm 1.5cm 2.5cm 1.5cm;
    
        @top-center {
        content: "Data Report";
        }
        @bottom-right {
            content: "Page" counter(page) " of " counter(page);
        }
    }
    </style>
</head>
<body>
{% block content %}
<table id="datatablesSimple">
    <tbody>
        <tr>
            <th scope="row">หมายเลขงาน</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">ประจำงวดงาน</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">ชื่อ Login ผู้แจ้งปัญหา</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">สถานที่ตั้งอุปกรณ์</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">หน่วยงาน</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">วันที่แจ้งปัญหา</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">ผู้แจ้งปัญหา</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">ปัญหาที่เกิดขึ้น</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">อุปกรณ์</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">ยี่ห้อ</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">รุ่น</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">หมายเลขคุรุภัณฑ์</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
        <tr>
            <th scope="row">หมายเลขประจำอุปกรณ์</th>
            <td style="padding-bottom: 5%;">...........</td>
        </tr>
    </tbody>
</table>
{% endblock %}
</body>
</html>

helpdeskproject/helpdeskapp/templates/helpdeskapp/doaction.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">
          {% if action == 'PROCESSING' %}
          กำลังซ่อม
          {% elif action == 'COMPLETE' %}
          ซ่อมเสร็จแล้ว
          {% elif action == 'CANCEL' %}
          ยกเลิก
          {% endif %}
        </h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>หมายเลขงาน</th>
                            <th>ประจำงวดงาน</th>
                            <th>ชื่อ Login ผู้แจ้งปัญหา</th>
                            <th>สถานที่ตั้งอุปกรณ์</th>
                            <th>หน่วยงาน</th>
                            <th>วันที่แจ้งปัญหา</th>
                            <th>ผู้แจ้งปัญหา</th>
                            <th>ปัญหาที่เกิดขึ้น</th>
                            <th>อุปกรณ์</th>
                            <th>ยี่ห้อ</th>
                            <th>รุ่น</th>
                            <th>หมายเลขคุรุภัณฑ์</th>
                            <th>หมายเลขประจำอุปกรณ์</th>
                            <th>มอบหมายงาน</th>
                            <th>รายละเอียดในการซ่อม</th>
                            <th>งานค้าง</th>
                            <th>วันที่ซ่อมเสร็จ</th>
                            <th>วันที่ส่งคืนอุปกรณ์</th>
                            <th>อุปกรณ์ Spare</th>
                            <th>วันที่ Spare อุปกรณ์</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for showdata in data_list %}
                        <tr>
                            <td>{{showdata.id}}</td>
                            <td>{{showdata.installment}}</td>
                            <td>{{showdata.user}}</td>
                            <td>{{showdata.place}}</td>
                            <td>{{showdata.institution}}</td>
                            <td>{{showdata.issue_date}}</td>
                            <td>{{showdata.informer}}</td>
                            <td>{{showdata.issue}}</td>
                            <td>{{showdata.device_name}}</td>
                            <td>{{showdata.brand}}</td>
                            <td>{{showdata.model}}</td>
                            <td>{{showdata.inventory_number}}</td>
                            <td>{{showdata.serial_number}}</td>
                            <td>{{showdata.delegation}}</td>
                            <td>{{showdata.detail}}</td>
                            <td>{{showdata.blocklog}}</td>
                            <td>{{showdata.job_complete_date}}</td>
                            <td>{{showdata.give_back_date}}</td>
                            <td>{{showdata.spare_device}}</td>
                            <td>{{showdata.spare_device_date}}</td>
                        </tr>
                        {% endfor %}  
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock %}

helpdeskproject/helpdeskapp/templates/helpdeskapp/mylist.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">แสดงรายละเอียดข้อมูล</h1>
            {% if messages %}
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                <b>{{message}}</b>
                {% endfor %}
            </div>
            {% endif %}    
        <div class="card mb-4">
            <div class="card-header"> 
                <i class="fas fa-table me-1"></i> 
                แสดงรายละเอียดข้อมูลทั้งหมด
            </div>
            <div class="card-body">
                <a href="{% url 'helpdeskapp:export-excel' %}" type="submit" class="btn btn-primary mb-3">Export Excel</a>
                <a href="{% url 'helpdeskapp:export-pdf' %}" type="submit" class="btn btn-primary mb-3">Export PDF</a>
                <a href="{% url 'helpdeskapp:export-blank-pdf' %}" type="submit" class="btn btn-primary mb-3">Export Blank PDF</a>
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>หมายเลขงาน</th>
                            <th>ชื่อ Login ผู้แจ้งปัญหา</th>
                            <th>ประจำงวดงาน</th>
                            <th>สถานที่ตั้งอุปกรณ์</th>
                            <th>หน่วยงาน</th>
                            <th>ผู้แจ้งปัญหา</th>
                            <th>เบอร์โทรศัพท์</th>
                            <th>วันที่แจ้งปัญหา</th>
                            <th>ปัญหาที่เกิดขึ้น</th>
                            <th>อุปกรณ์</th>
                            <th>ยี่ห้อ</th>
                            <th>รุ่น</th>
                            <th>หมายเลขคุรุภัณฑ์</th>
                            <th>หมายเลขประจำอุปกรณ์</th>
                            <th>มอบหมายงาน</th>
                            <th>ผู้รับผิดชอบ</th>
                            <th>รายละเอียดในการซ่อม</th>
                            <th>งานค้าง</th>
                            <th>สถานะการซ่อมบำรุง</th>
                            <th>วันที่ซ่อมเสร็จ</th>
                            <th>หมายเหตุ</th>
                            <th>วันที่ส่งคืนอุปกรณ์</th>
                            <th>อุปกรณ์ Spare</th>
                            <th>หมายเลขประจำอุปกรณ์</th>
                            <th>วันที่ Spare อุปกรณ์</th>
                            <th>วันที่นำ Spare กลับบริษัท</th>
                            <th>เปลี่ยนอุปกรณ์หรือไม่?</th>
                            <th>อุปกรณ์ที่เปลี่ยน</th>
                            <th>ยี่ห้อ</th>
                            <th>รุ่น</th>
                            <th>หมายเลขอุปกรณ์ที่เปลี่ยน</th>
                            <th>ภาพก่อนซ่อม</th>
                            <th>ภาพหลังซ่อม</th>
                            <th>จัดการ</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for showdata in ticket_list%}
                        <tr>
                            <td width='100px'>{{showdata.id}}</td>
                            <td>{{showdata.user}}</td>
                            <td>{{showdata.installment}}</td>
                            <td>{{showdata.place}}</td>
                            <td>{{showdata.institution}}</td>
                            <td>{{showdata.informer}}</td>
                            <td>{{showdata.phone_number}}</td>
                            <td>{{showdata.issue_date}}</td>
                            <td>{{showdata.issue}}</td>
                            <td>{{showdata.device_name}}</td>
                            <td>{{showdata.brand}}</td>
                            <td>{{showdata.model}}</td>
                            <td>{{showdata.inventory_number}}</td>
                            <td>{{showdata.serial_number}}</td>
                            <td>{{showdata.delegation}}</td>
                            <td>{{showdata.responsibility}}</td>
                            <td>{{showdata.detail}}</td>
                            <td>{{showdata.blocklog}}</td>
                            <td>{{showdata.status}}</td>
                            <td>{{showdata.job_complete_date}}</td>
                            <td>{{showdata.reason}}</td>
                            <td>{{showdata.give_back_date}}</td>
                            <td>{{showdata.spare_device}}</td>
                            <td>{{showdata.serial_number_spare}}</td>
                            <td>{{showdata.spare_device_date}}</td>
                            <td>{{showdata.got_back_spare_device_date}}</td>
                            <td>{{showdata.change_device}}</td>
                            <td>{{showdata.change_device_name}}</td>
                            <td>{{showdata.change_for_brand}}</td>
                            <td>{{showdata.change_for_model}}</td>
                            <td>{{showdata.change_for_serial_number}}</td>
                            
                            <td>{% if showdata.upload_image_before %}
                                <a href="{{showdata.upload_image_before.url}}" download> ดาวน์โหลด</a>
                            {% endif %}</td>
                            <td>{% if showdata.upload_image_after %}
                                <a href="{{showdata.upload_image_after.url}}" download> ดาวน์โหลด</a>
                            {% endif %}</td>
                            <td><a href="{% url 'helpdeskapp:edit' showdata.id %}" class="btn btn-warning" id="edit" name="edit" value="edit">แก้ไข</a></td>
                        </tr> 
                        {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock %}