helpdeskproject/helpdeskapp/urls.py
from django.urls import path
from . import views

app_name = 'helpdeskapp'

urlpatterns = [
    path('adds/', views.adds, name='adds'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('mylist/', views.mylist, name='mylist'),
    path('query_data/', views.query_data, name='query_data'),
    path('doaction/<action>', views.DoAction, name='DoAction'),
    path('export_pdf/', views.export_pdf, name='export-pdf'),
    path('export_excel/', views.export_excel, name='export-excel'),
    path('export_blank_pdf/', views.export_blank_pdf, name='export-blank-pdf'),
]

helpdeskproject/helpdeskproject/urls.py
from django.contrib import admin
from django.urls import path, include
from helpdeskapp import views
from django.conf import settings
from django.conf.urls.static import static
#from helpdeskapp.views import mychartview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('helpdeskapp/', include('helpdeskapp.urls')),
    path('helpdeskusers/', include('helpdeskusers.urls')),
    #path('', mychartview.as_view(), name='home'),
    path('', views.mychartview, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpdeskproject/helpdeskusers/urls.py
from django.urls import path
from helpdeskusers import views
from django.contrib.auth import views as auth_views

app_name = 'helpdeskusers'

urlpatterns = [

    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='helpdeskusers/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='helpdeskusers/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='helpdeskusers/reset_password.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordChangeDoneView.as_view(template_name='helpdeskusers/reset_password_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='helpdeskusers/reset_password_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='helpdeskusers/reset_password_complete.html'), name='password_reset_complete'),
]

helpdeskproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>HelpDesk</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.2/chart.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'home' %}">HelpDesk</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" method="get" role="form" action="">
                <div class="input-group">
                    <select class="form-select mx-2" name="search-box" aria-label="Default select example">
                        <option selected>เลือกเมนูเพื่อค้นหา</option>
                        <option value="Everything">Everything</option>
                        <option value="Titles">Titles</option>
                        <option value="Descriptions">Descriptions</option>
                      </select>
                    <input class="form-control" type="text" name="q" placeholder="ค้นหา ..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="submit" name="search"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                    <i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'helpdeskusers:login' %}">Logout</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'helpdeskusers:profile' %}">Settings</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'helpdeskusers:login' %}">Login</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'helpdeskusers:register' %}">Register</a></li>
                        {% endif %}
                        
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{% url 'home' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="{% url 'home' %}" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                                Home
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-database"></i></div>
                                Query
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav" id="sidenavAccordionPages">
                                    <a class="nav-link" href="{% url 'helpdeskapp:DoAction' 'PROCESSING' %}">แสดงข้อมูลกำลังซ่อม</a>
                                    <a class="nav-link" href="{% url 'helpdeskapp:DoAction' 'COMPLETE' %}">แสดงข้อมูลซ่อมเสร็จแล้ว</a>
                                    <a class="nav-link" href="{% url 'helpdeskapp:DoAction' 'CANCEL' %}">แสดงข้อมูลยกเลิก</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="" data-bs-toggle="collapse" data-bs-target="#collapseForms" aria-expanded="false" aria-controls="collapseForms">
                                <div class="sb-nav-link-icon"><i class="fab fa-wpforms"></i></div>
                                Forms
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseForms" aria-labelledby="headingThree" data-bs-parent="#sidenavAccordition">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'helpdeskapp:adds' %}">เพิ่ม</a>
                                    <a class="nav-link" href="{% url 'helpdeskapp:mylist' %}">แสดงข้อมูลทั้งหมด</a>
                                </nav>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    {% block content %}
                    {% endblock %}
                    
                    {% block scripts %}
                    {% endblock %}
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        
    </body>
</html>